# Generated by Django 2.2 on 2019-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190414_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='placeholder'),
            preserve_default=False,
        ),
    ]
