# Generated by Django 2.2 on 2019-05-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20190514_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='vievs',
            new_name='views',
        ),
    ]
